Fix: automate - Improve yaml loader
bluebanquise/community pull request #49
Opened 2022-01-03 21:36 UTC by oxedions

2022-01-04 08:20 UTC, strus38 commented
Hi
While reviewing this role, I would change the way you are handling python dependencies.
I think it would be better and more flexible to add a requirements.txt file with all python dependencies and as a task, either load the RPMs as you did or enable to install it through pip3. For flask/Celery it is way better to use a venv than using system dependencies.

2022-01-04 22:39 UTC, neilmunday requested changes

2022-01-04 22:39 UTC, neilmunday commented on roles/automate/files/bbautomate.py
> +        yaml_loader='Safe'
Rather using a hard coded string, why not use a Boolean variable instead? E.g.

```
yaml_loader_safe = False
if yaml_version_major > 5 or (yaml_version_major == 5 and yaml_version_minor >= 1):
    yaml_loader_safe = True
```

2022-01-04 22:39 UTC, neilmunday commented on roles/automate/files/bbautomate.py
> +        if yaml_loader == 'Safe':
Following on from previous comment:

```
if yaml_loader_safe:
    return yaml.load(f, Loader=yaml.FullLoader)
return yaml.load(f)
```

Note: the `else` is not needed due to the first `return`

2022-01-05 21:33 UTC, oxedions commented
@neilmunday Should be better now 🙂

2022-01-05 21:35 UTC, oxedions commented
> Hi While reviewing this role, I would change the way you are handling python dependencies. I think it would be better and more flexible to add a requirements.txt file with all python dependencies and as a task, either load the RPMs as you did or enable to install it through pip3. For flask/Celery it is way better to use a venv than using system dependencies.

Ok, so you mean that using a variable (for example `automate_dependencies`), the role would either install packages, or trigger a pip Ansible module (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html) combined with a requirement.txt file to install dependencies via pip ? Do I understand well ?

2022-01-05 21:43 UTC, neilmunday approved these changes

2022-01-06 13:37 UTC, oxedions commented
@neilmunday thanks for the review !
@strus38 I will open an issue to continue our exchange.

2022-01-06 13:37 UTC, merged