Fix: podman - Use slirp4netns to avoid error with HA
bluebanquise/community pull request #65
Opened 2022-05-06 16:59 UTC by ginomcevoy

Previous PR #38 mentioned an issue with podman containers and firewall, that results in a "Connection refused" error. While the explanation in the PR is correct (containers lose connectivity after a firewall reload), there is another situation that the error happens: after pacemaker begins to manage the systemd service for the first time in a High Availability scenario. We have reproduced this issue consistently with VMs, but it only happened the first time the service is started by pacemaker on each node.

This PR implements a fix proposed in the previous PR, to use the slirp4netns user-mode networking for the systemd service. This solution is used for unprivileged containers by default, but it can also be used for privileged containers. We have not found any downsides of using slirp4netns in this and other privileged container services.

2022-05-06 17:08 UTC, strus38 submitted a review, later dismissed

2022-05-06 17:09 UTC, ginomcevoy commented
FYI, this fix has been known and patched on our side for some time now, I forgot to push it to Bluebanquise until now :)

2022-05-06 17:21 UTC, ginomcevoy commented
Forgot to update CHANGELOG.md, so I added one more commit.

2022-05-07 19:47 UTC, neilmunday requested changes
Looks good but can you address the workflow checks that failed please?

2022-05-09 10:55 UTC, ginomcevoy commented
Hello @neilmunday , I see "All checks have passed", could you please point me to the workflow checks that failed?

2022-05-09 10:59 UTC, ginomcevoy commented
OK I found "Unchanged files with check annotations" with some FQCN and yaml warnings, in the "singularity" and "podman" roles. Do you want me to take care of these in this PR?

2022-05-09 15:44 UTC, strus38 commented
You may let those all... I will fix them separately in all my roles.

Le lun. 9 mai 2022 à 12:59, Giacomo Mc Evoy ***@***.***> a
écrit :

> OK I found "Unchanged files with check annotations" with some FQCN and
> yaml warnings, in the "singularity" and "podman" roles. Do you want me to
> take care of these in this PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bluebanquise/community/pull/65#issuecomment-1120952036>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABM6DUZWHRTHYCZZABEBENLVJDVY5ANCNFSM5VIWYPZA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-05-09 20:08 UTC, neilmunday commented
> OK I found "Unchanged files with check annotations" with some FQCN and yaml warnings, in the "singularity" and "podman" roles. Do you want me to take care of these in this PR?

Apologies, I didn't realise the checks were for other files.

2022-05-09 20:09 UTC, neilmunday approved these changes

2022-05-10 09:24 UTC, merged