Updating Grafana role for enhancements
bluebanquise/community pull request #9
Opened 2021-04-07 08:24 UTC by strus38

A huge enhancement for the grafana role to allow:
- customizing the grafane deployment with port, dashboards, ldap, etc...

2021-04-16 21:03 UTC, oxedions requested changes
Dear @strus38 

Many thanks for this massive and impressive dev. 😊 

I tested the role basic features (installing grafana, setting user/pass, firewall, adding a dashboard, adding a datasource) with success, but had issues with dashboards. See my comments on that point.

I also think it could be interesting in the README to point somewhere to https://grafana.com/grafana/download so users know where to download it.

Also, could you change the owner of the role and become the owner ?

Regarding automatic tests, since I am way to late to provide them, I understand you added them in this PR, and I am ok with that.

2021-04-16 21:03 UTC, oxedions commented on roles/grafana/README.md
> +grafana_dashboards:
I tried dashboards. In fact, the role imported my json files I put i my **dashboards** folder, but ignored the ids list here.

So importing json is working, but not really documented, and importing id does not seems to work.

2021-07-12 15:46 UTC, strus38 commented
Fixed issues... working like a charm 👍

2021-07-13 21:07 UTC, oxedions approved these changes
Dear @strus38 

Thanks a lot for this PR.

It is ok for me 😊

2021-07-14 08:26 UTC, strus38 commented
> Dear @strus38
> 
> Thanks a lot for this PR.
> 
> It is ok for me 😊

I will try to fix the automated tests... not sure why some are failing.

2021-07-14 18:41 UTC, strus38 commented
Finally got the CICD successful ... you can re-approve!! @oxedions  ... sorry for all that, but the only way to validate is to run it by committing more fixes :-)

2021-07-19 20:49 UTC, oxedions commented
I understand 😊 

Restarting checks.

2021-07-19 21:50 UTC, merged

2021-07-19 21:50 UTC, oxedions commented
All green, merged. Many thanks 😉